backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "src/assets/uploads" # Media files will be stored in the repo under src/assets/uploads
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with /assets/uploads

collections:
  - name: "settings"
    label: "General Settings"
    files:
      - file: "src/data/settings.json"
        label: "Global Settings"
        name: "settings"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Contact Phone Number", name: "phone", widget: "string" }
          - { label: "Contact Email", name: "email", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/pages/homepage.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Headline", name: "hero_headline", widget: "string" }
          - { label: "Hero Subheadline", name: "hero_subheadline", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "SEO Settings"
            name: "seo"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Meta Title (leave blank to use page title)", name: "title", widget: "string", required: false }
              - { label: "Meta Description", name: "description", widget: "text", required: false, hint: "150-160 characters ideal" }
              - { label: "Focus Keywords", name: "keywords", widget: "string", required: false, hint: "Comma separated" }
              - { label: "Featured Image", name: "image", widget: "image", required: false }
              - { label: "Alt Text for Featured Image", name: "imageAlt", widget: "string", required: false }
              - { label: "Hide from Search Engines", name: "noindex", widget: "boolean", default: false }
              - { label: "Canonical URL (advanced)", name: "canonical", widget: "string", required: false }
      - file: "src/content/pages/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "SEO Settings"
            name: "seo"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Meta Title (leave blank to use page title)", name: "title", widget: "string", required: false }
              - { label: "Meta Description", name: "description", widget: "text", required: false, hint: "150-160 characters ideal" }
              - { label: "Focus Keywords", name: "keywords", widget: "string", required: false, hint: "Comma separated" }
              - { label: "Featured Image", name: "image", widget: "image", required: false }
              - { label: "Alt Text for Featured Image", name: "imageAlt", widget: "string", required: false }
              - { label: "Hide from Search Engines", name: "noindex", widget: "boolean", default: false }
              - { label: "Canonical URL (advanced)", name: "canonical", widget: "string", required: false }

  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "SEO Settings"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Meta Title (leave blank to use page title)", name: "title", widget: "string", required: false }
          - { label: "Meta Description", name: "description", widget: "text", required: false, hint: "150-160 characters ideal" }
          - { label: "Focus Keywords", name: "keywords", widget: "string", required: false, hint: "Comma separated" }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Alt Text for Featured Image", name: "imageAlt", widget: "string", required: false }
          - { label: "Hide from Search Engines", name: "noindex", widget: "boolean", default: false }
          - { label: "Canonical URL (advanced)", name: "canonical", widget: "string", required: false }

  - name: "case_studies"
    label: "Case Studies"
    folder: "src/content/case_studies"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Customer Name", name: "customer", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "SEO Settings"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Meta Title (leave blank to use page title)", name: "title", widget: "string", required: false }
          - { label: "Meta Description", name: "description", widget: "text", required: false, hint: "150-160 characters ideal" }
          - { label: "Focus Keywords", name: "keywords", widget: "string", required: false, hint: "Comma separated" }
          - { label: "Featured Image", name: "image", widget: "image", required: false }
          - { label: "Alt Text for Featured Image", name: "imageAlt", widget: "string", required: false }
          - { label: "Hide from Search Engines", name: "noindex", widget: "boolean", default: false }
          - { label: "Canonical URL (advanced)", name: "canonical", widget: "string", required: false }

  # Business Information Collection (for Schema markup)
  - name: "business"
    label: "Business Info"
    files:
      - label: "Company Information"
        name: "company"
        file: "src/content/business/company.md"
        fields:
          - { label: "Company Name", name: "name", widget: "string", default: "Custom Climates" }
          - { label: "Phone Number", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Street Address", name: "address", widget: "string" }
          - { label: "City", name: "city", widget: "string" }
          - { label: "State", name: "state", widget: "string" }
          - { label: "ZIP Code", name: "zip", widget: "string" }
          - { label: "Business Hours", name: "hours", widget: "text" }
          - label: "Service Areas"
            name: "serviceAreas"
            widget: "list"
            field: { label: "Location", name: "location", widget: "string" }

  # Global SEO Settings Collection
  - name: "seo_settings"
    label: "Global SEO Settings"
    files:
      - label: "Global SEO"
        name: "seo"
        file: "src/content/settings/seo.md"
        fields:
          - { label: "Default Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Default Keywords", name: "keywords", widget: "string" }
          - { label: "Default Share Image", name: "image", widget: "image" }
          - { label: "Company Logo", name: "logo", widget: "image" }
          - { label: "Favicon", name: "favicon", widget: "image" }
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
              - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
              - { label: "Twitter/X Handle", name: "twitter", widget: "string", required: false }
          - label: "Analytics"
            name: "analytics"
            widget: "object"
            fields:
              - { label: "Google Analytics ID", name: "googleAnalytics", widget: "string", required: false }
              - { label: "Google Tag Manager ID", name: "gtm", widget: "string", required: false } 