backend:
  name: github
  repo: your-github-username/custom-climates # e.g. "my-user/my-repo"
  branch: main

local_backend: true

media_folder: "src/assets/uploads" # Media files will be stored in the repo here
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with /assets/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/content/pages/homepage.md"
        fields:
          - { label: "Hero Headline", name: "hero_headline", widget: "string" }
          - { label: "Hero Subtext", name: "hero_subtext", widget: "string" }

  - name: "equipment"
    label: "Equipment"
    folder: "src/content/equipment"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Features", name: "features", widget: "list" }